api_login_check:
    path: /api/login_check

custom_token:
    path: /login/custom_token
    controller: App\Controller\Login::CustomInformationToken
    methods: [GET]

api_profile:
    path: /api/profile
    controller: App\Controller\Profile::me
    methods: [GET]

api_registrar_usuario:
    path: /registrar
    controller: App\Controller\RegistrarController::nuevoUsuario
    methods: [POST]

api_mostrar_formulario_registrar:
    path: /registrar
    controller: App\Controller\RegistrarController::mostrarFormulario
    methods: [GET]
