api_login_check:
    path: /api/login_check

api_profile:
    path: /api/profile
    controller: App\Controller\Profile::mostrarCliente
    methods: [GET]

api_registrar_usuario:
    path: /registrar
    controller: App\Controller\RegistrarController::nuevoUsuario
    methods: [POST]

api_mostrar_formulario_registrar:
    path: /registrar
    controller: App\Controller\RegistrarController::mostrarFormulario
    methods: [GET]
